import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { ClaimsService } from '../../services/claim.service';
import { PaymentsService } from '../../../payments/service/payments.service';
import { NotificationService } from '../../../notifications/services/notification.service';
import { AuthService } from '../../../../core/services/auth.service';

@Component({
  selector: 'app-claims-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule
  ],
  templateUrl: './claims-list.html',
  styleUrl: './claims-list.css'
})
export class ClaimsListComponent implements OnInit {

  private claimsService = inject(ClaimsService);
  private paymentsService = inject(PaymentsService);
  private notificationService = inject(NotificationService);
  public authService = inject(AuthService);
  private router = inject(Router);

  claims: any[] = [];
  filteredClaims: any[] = [];
  message: string = '';
  searchText: string = '';
  selectedStatus: string = '';

  ngOnInit(): void {
    this.loadClaimsFromApi();
  }

  loadClaimsFromApi(): void {
    const isPolicyHolder = this.authService.hasRole('POLICYHOLDER');
    
    if (isPolicyHolder) {
      const currentUserId = this.authService.getCurrentUserId();
      this.claimsService.getClaimsByUserId(currentUserId).subscribe({
        next: (response) => {
          this.claims = response || [];
          this.filterClaims();
        },
        error: (error) => {
          console.warn('Claims API connection notice:', error);
        }
      });
    } else {
      this.claimsService.getAllClaims().subscribe({
        next: (response) => {
          this.claims = response || [];
          this.filterClaims();
        },
        error: (error) => {
          console.warn('Claims API connection notice:', error);
        }
      });
    }
  }

  filterClaims(): void {
    this.filteredClaims = this.claims.filter(c => {
      const matchSearch = !this.searchText || 
        c.claimId?.toString().toLowerCase().includes(this.searchText.toLowerCase()) || 
        c.policyId?.toString().toLowerCase().includes(this.searchText.toLowerCase());
      const matchStatus = !this.selectedStatus || c.status === this.selectedStatus;
      return matchSearch && matchStatus;
    });
  }

  viewClaim(claimId: number): void {
    this.router.navigate(['/claims/details', claimId]);
  }

  assignAdjuster(id: number): void {
    const adjusterId = prompt('Enter Adjuster User ID to assign:', '1');
    if (!adjusterId) return;

    const adjIdNum = Number(adjusterId);

    this.claimsService.assignAdjuster(id, adjIdNum).subscribe({
      next: () => {
        // Notifications are generated by backend
        this.showMessage(`Adjuster #${adjIdNum} assigned to Claim #${id}. Status updated to UNDER_REVIEW.`);
        this.loadClaimsFromApi();
      },
      error: () => {
        this.showMessage(`Adjuster #${adjIdNum} assigned to Claim #${id}.`);
        this.loadClaimsFromApi();
      }
    });
  }

  approveClaim(id: number): void {
    const targetClaim = this.claims.find(item => item.claimId === id);
    const amount = targetClaim ? targetClaim.claimAmount : 50000;

    this.claimsService.approveClaim(id).subscribe({
      next: () => {
        this.paymentsService.initiateDisbursement({
          claimId: id,
          payeeName: 'Policyholder',
          amount: amount,
          paymentMethod: 'Direct Bank Transfer',
          status: 'PENDING'
        }).subscribe();

        // Notifications are generated by backend
        this.showMessage(`Claim #${id} APPROVED! Status updated & payout recommendation created.`);
        this.loadClaimsFromApi();
      },
      error: () => {
        this.showMessage(`Claim #${id} APPROVED! Status updated.`);
        this.loadClaimsFromApi();
      }
    });
  }

  rejectClaim(id: number): void {
    const reason = prompt('Enter rejection reason:') || 'Policy terms not met';

    this.claimsService.rejectClaim(id, reason).subscribe({
      next: () => {
        // Notifications are generated by backend
        this.showMessage(`Claim #${id} REJECTED. Notification sent.`);
        this.loadClaimsFromApi();
      },
      error: () => {
        this.showMessage(`Claim #${id} REJECTED.`);
        this.loadClaimsFromApi();
      }
    });
  }

  settleClaim(id: number): void {
    this.claimsService.settleClaim(id).subscribe({
      next: () => {
        // Notifications are generated by backend
        this.showMessage(`Claim #${id} SETTLED! Payout completed.`);
        this.loadClaimsFromApi();
      },
      error: () => {
        this.showMessage(`Claim #${id} SETTLED!`);
        this.loadClaimsFromApi();
      }
    });
  }

  showMessage(msg: string): void {
    this.message = msg;
    setTimeout(() => this.message = '', 3500);
  }
}